List<String> titlesList = [
  'The person who never made a mistake never made anything',
  'When something goes wrong in life, just shout \"plot twist!\" and carry on.',
  'Make choices and dont look back',
  'Never regret. If it\'s good it\'s wonderful. If it\'s bad it\'s an experience.',
  'One of the top five regrets people have is that they didn\'t have the courage to be their true self.',
  'Valuing the people in your life',
  'EveryBody makes mistakes',
  'If you cant\'t believe on yourself someday , believe on the Almighty because he believes on you everyday.',
  'AI Jobs for the win?',
  'Will threads destroy Twitter?',
  'Effect of AI generative tools on Journalism',
  'Biggest controversy of your life',
  'Experience you would remember the whole lif(you can change the Title)',
  'Women Bill passed by the government',
];
